"""
Auto-generated from fpscanner_ref/types.ts on 2026-04-26 10:16:15 UTC.
DO NOT EDIT — run `python init/generate_schema.py` to regenerate.
"""

# ── Signal fields (from FingerprintSignals interface) ──

SIGNAL_FIELDS = [
    {"path": "automation.webdriver", "column": "automation_webdriver", "label": "Automation > Webdriver", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "automation.webdriverWritable", "column": "automation_webdriver_writable", "label": "Automation > Webdriver Writable", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "automation.selenium", "column": "automation_selenium", "label": "Automation > Selenium", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "automation.cdp", "column": "automation_cdp", "label": "Automation > CDP", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "automation.playwright", "column": "automation_playwright", "label": "Automation > Playwright", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "automation.navigatorPropertyDescriptors", "column": "automation_navigator_property_descriptors", "label": "Automation > Navigator Property Descriptors", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "device.cpuCount", "column": "device_cpu_count", "label": "Device > CPU Count", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.memory", "column": "device_memory", "label": "Device > Memory", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.platform", "column": "device_platform", "label": "Device > Platform", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "device.screenResolution.width", "column": "device_screen_resolution_width", "label": "Device > Screen Resolution > Width", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.height", "column": "device_screen_resolution_height", "label": "Device > Screen Resolution > Height", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.pixelDepth", "column": "device_screen_resolution_pixel_depth", "label": "Device > Screen Resolution > Pixel Depth", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.colorDepth", "column": "device_screen_resolution_color_depth", "label": "Device > Screen Resolution > Color Depth", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.availableWidth", "column": "device_screen_resolution_available_width", "label": "Device > Screen Resolution > Available Width", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.availableHeight", "column": "device_screen_resolution_available_height", "label": "Device > Screen Resolution > Available Height", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.innerWidth", "column": "device_screen_resolution_inner_width", "label": "Device > Screen Resolution > Inner Width", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.innerHeight", "column": "device_screen_resolution_inner_height", "label": "Device > Screen Resolution > Inner Height", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.screenResolution.hasMultipleDisplays", "column": "device_screen_resolution_has_multiple_displays", "label": "Device > Screen Resolution > Has Multiple Displays", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "device.multimediaDevices.speakers", "column": "device_multimedia_devices_speakers", "label": "Device > Multimedia Devices > Speakers", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.multimediaDevices.microphones", "column": "device_multimedia_devices_microphones", "label": "Device > Multimedia Devices > Microphones", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.multimediaDevices.webcams", "column": "device_multimedia_devices_webcams", "label": "Device > Multimedia Devices > Webcams", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "device.mediaQueries.prefersColorScheme", "column": "device_media_queries_prefers_color_scheme", "label": "Device > Media Queries > Prefers Color Scheme", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "device.mediaQueries.prefersReducedMotion", "column": "device_media_queries_prefers_reduced_motion", "label": "Device > Media Queries > Prefers Reduced Motion", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "device.mediaQueries.prefersReducedTransparency", "column": "device_media_queries_prefers_reduced_transparency", "label": "Device > Media Queries > Prefers Reduced Transparency", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "device.mediaQueries.colorGamut", "column": "device_media_queries_color_gamut", "label": "Device > Media Queries > Color Gamut", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "device.mediaQueries.pointer", "column": "device_media_queries_pointer", "label": "Device > Media Queries > Pointer", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "device.mediaQueries.anyPointer", "column": "device_media_queries_any_pointer", "label": "Device > Media Queries > Any Pointer", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "device.mediaQueries.hover", "column": "device_media_queries_hover", "label": "Device > Media Queries > Hover", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "device.mediaQueries.anyHover", "column": "device_media_queries_any_hover", "label": "Device > Media Queries > Any Hover", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "device.mediaQueries.colorDepth", "column": "device_media_queries_color_depth", "label": "Device > Media Queries > Color Depth", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "browser.userAgent", "column": "browser_user_agent", "label": "Browser > User Agent", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.features.bitmask", "column": "browser_features_bitmask", "label": "Browser > Features > Bitmask", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.features.chrome", "column": "browser_features_chrome", "label": "Browser > Features > Chrome", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.brave", "column": "browser_features_brave", "label": "Browser > Features > Brave", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.applePaySupport", "column": "browser_features_apple_pay_support", "label": "Browser > Features > Apple Pay Support", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.opera", "column": "browser_features_opera", "label": "Browser > Features > Opera", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.serial", "column": "browser_features_serial", "label": "Browser > Features > Serial", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.attachShadow", "column": "browser_features_attach_shadow", "label": "Browser > Features > Attach Shadow", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.caches", "column": "browser_features_caches", "label": "Browser > Features > Caches", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.webAssembly", "column": "browser_features_web_assembly", "label": "Browser > Features > Web Assembly", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.buffer", "column": "browser_features_buffer", "label": "Browser > Features > Buffer", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.showModalDialog", "column": "browser_features_show_modal_dialog", "label": "Browser > Features > Show Modal Dialog", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.safari", "column": "browser_features_safari", "label": "Browser > Features > Safari", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.webkitPrefixedFunction", "column": "browser_features_webkit_prefixed_function", "label": "Browser > Features > Webkit Prefixed Function", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.mozPrefixedFunction", "column": "browser_features_moz_prefixed_function", "label": "Browser > Features > Moz Prefixed Function", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.usb", "column": "browser_features_usb", "label": "Browser > Features > USB", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.browserCapture", "column": "browser_features_browser_capture", "label": "Browser > Features > Browser Capture", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.paymentRequestUpdateEvent", "column": "browser_features_payment_request_update_event", "label": "Browser > Features > Payment Request Update Event", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.pressureObserver", "column": "browser_features_pressure_observer", "label": "Browser > Features > Pressure Observer", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.audioSession", "column": "browser_features_audio_session", "label": "Browser > Features > Audio Session", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.selectAudioOutput", "column": "browser_features_select_audio_output", "label": "Browser > Features > Select Audio Output", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.barcodeDetector", "column": "browser_features_barcode_detector", "label": "Browser > Features > Barcode Detector", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.battery", "column": "browser_features_battery", "label": "Browser > Features > Battery", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.devicePosture", "column": "browser_features_device_posture", "label": "Browser > Features > Device Posture", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.documentPictureInPicture", "column": "browser_features_document_picture_in_picture", "label": "Browser > Features > Document Picture In Picture", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.eyeDropper", "column": "browser_features_eye_dropper", "label": "Browser > Features > Eye Dropper", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.editContext", "column": "browser_features_edit_context", "label": "Browser > Features > Edit Context", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.fencedFrame", "column": "browser_features_fenced_frame", "label": "Browser > Features > Fenced Frame", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.sanitizer", "column": "browser_features_sanitizer", "label": "Browser > Features > Sanitizer", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.features.otpCredential", "column": "browser_features_otp_credential", "label": "Browser > Features > OTP Credential", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.plugins.isValidPluginArray", "column": "browser_plugins_is_valid_plugin_array", "label": "Browser > Plugins > Is Valid Plugin Array", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.plugins.pluginCount", "column": "browser_plugins_plugin_count", "label": "Browser > Plugins > Plugin Count", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "browser.plugins.pluginNamesHash", "column": "browser_plugins_plugin_names_hash", "label": "Browser > Plugins > Plugin Names Hash", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.plugins.pluginConsistency1", "column": "browser_plugins_plugin_consistency1", "label": "Browser > Plugins > Plugin Consistency1", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.plugins.pluginOverflow", "column": "browser_plugins_plugin_overflow", "label": "Browser > Plugins > Plugin Overflow", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.extensions.bitmask", "column": "browser_extensions_bitmask", "label": "Browser > Extensions > Bitmask", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.extensions.extensions", "column": "browser_extensions_extensions", "label": "Browser > Extensions > Extensions", "type": "string", "sa_type": "JSONB", "default": list},
    {"path": "browser.highEntropyValues.architecture", "column": "browser_high_entropy_values_architecture", "label": "Browser > High Entropy Values > Architecture", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.highEntropyValues.bitness", "column": "browser_high_entropy_values_bitness", "label": "Browser > High Entropy Values > Bitness", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.highEntropyValues.brands", "column": "browser_high_entropy_values_brands", "label": "Browser > High Entropy Values > Brands", "type": "string", "sa_type": "JSONB", "default": list},
    {"path": "browser.highEntropyValues.mobile", "column": "browser_high_entropy_values_mobile", "label": "Browser > High Entropy Values > Mobile", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "browser.highEntropyValues.model", "column": "browser_high_entropy_values_model", "label": "Browser > High Entropy Values > Model", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.highEntropyValues.platform", "column": "browser_high_entropy_values_platform", "label": "Browser > High Entropy Values > Platform", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.highEntropyValues.platformVersion", "column": "browser_high_entropy_values_platform_version", "label": "Browser > High Entropy Values > Platform Version", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.highEntropyValues.uaFullVersion", "column": "browser_high_entropy_values_ua_full_version", "label": "Browser > High Entropy Values > UA Full Version", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.etsl", "column": "browser_etsl", "label": "Browser > ETSL", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "browser.maths", "column": "browser_maths", "label": "Browser > Maths", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.toSourceError.toSourceError", "column": "browser_to_source_error_to_source_error", "label": "Browser > To Source Error > To Source Error", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "browser.toSourceError.hasToSource", "column": "browser_to_source_error_has_to_source", "label": "Browser > To Source Error > Has To Source", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "graphics.webGL.vendor", "column": "graphics_web_gl_vendor", "label": "Graphics > WebGL > Vendor", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "graphics.webGL.renderer", "column": "graphics_web_gl_renderer", "label": "Graphics > WebGL > Renderer", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "graphics.webgpu.vendor", "column": "graphics_webgpu_vendor", "label": "Graphics > WebGPU > Vendor", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "graphics.webgpu.architecture", "column": "graphics_webgpu_architecture", "label": "Graphics > WebGPU > Architecture", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "graphics.webgpu.device", "column": "graphics_webgpu_device", "label": "Graphics > WebGPU > Device", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "graphics.webgpu.description", "column": "graphics_webgpu_description", "label": "Graphics > WebGPU > Description", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "graphics.canvas.hasModifiedCanvas", "column": "graphics_canvas_has_modified_canvas", "label": "Graphics > Canvas > Has Modified Canvas", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "graphics.canvas.canvasFingerprint", "column": "graphics_canvas_canvas_fingerprint", "label": "Graphics > Canvas > Canvas Fingerprint", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "codecs.audioCanPlayTypeHash", "column": "codecs_audio_can_play_type_hash", "label": "Codecs > Audio Can Play Type Hash", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "codecs.videoCanPlayTypeHash", "column": "codecs_video_can_play_type_hash", "label": "Codecs > Video Can Play Type Hash", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "codecs.audioMediaSourceHash", "column": "codecs_audio_media_source_hash", "label": "Codecs > Audio Media Source Hash", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "codecs.videoMediaSourceHash", "column": "codecs_video_media_source_hash", "label": "Codecs > Video Media Source Hash", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "codecs.rtcAudioCapabilitiesHash", "column": "codecs_rtc_audio_capabilities_hash", "label": "Codecs > RTC Audio Capabilities Hash", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "codecs.rtcVideoCapabilitiesHash", "column": "codecs_rtc_video_capabilities_hash", "label": "Codecs > RTC Video Capabilities Hash", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "codecs.hasMediaSource", "column": "codecs_has_media_source", "label": "Codecs > Has Media Source", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "locale.internationalization.timezone", "column": "locale_internationalization_timezone", "label": "Locale > Internationalization > Timezone", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "locale.internationalization.localeLanguage", "column": "locale_internationalization_locale_language", "label": "Locale > Internationalization > Locale Language", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "locale.languages.languages", "column": "locale_languages_languages", "label": "Locale > Languages > Languages", "type": "string", "sa_type": "JSONB", "default": list},
    {"path": "locale.languages.language", "column": "locale_languages_language", "label": "Locale > Languages > Language", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.iframe.webdriver", "column": "contexts_iframe_webdriver", "label": "Contexts > Iframe > Webdriver", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "contexts.iframe.userAgent", "column": "contexts_iframe_user_agent", "label": "Contexts > Iframe > User Agent", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.iframe.platform", "column": "contexts_iframe_platform", "label": "Contexts > Iframe > Platform", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.iframe.memory", "column": "contexts_iframe_memory", "label": "Contexts > Iframe > Memory", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "contexts.iframe.cpuCount", "column": "contexts_iframe_cpu_count", "label": "Contexts > Iframe > CPU Count", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "contexts.iframe.language", "column": "contexts_iframe_language", "label": "Contexts > Iframe > Language", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.webWorker.webdriver", "column": "contexts_web_worker_webdriver", "label": "Contexts > Web Worker > Webdriver", "type": "boolean", "sa_type": "db.Boolean", "default": False},
    {"path": "contexts.webWorker.userAgent", "column": "contexts_web_worker_user_agent", "label": "Contexts > Web Worker > User Agent", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.webWorker.platform", "column": "contexts_web_worker_platform", "label": "Contexts > Web Worker > Platform", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.webWorker.memory", "column": "contexts_web_worker_memory", "label": "Contexts > Web Worker > Memory", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "contexts.webWorker.cpuCount", "column": "contexts_web_worker_cpu_count", "label": "Contexts > Web Worker > CPU Count", "type": "number", "sa_type": "db.Float", "default": 0},
    {"path": "contexts.webWorker.language", "column": "contexts_web_worker_language", "label": "Contexts > Web Worker > Language", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.webWorker.vendor", "column": "contexts_web_worker_vendor", "label": "Contexts > Web Worker > Vendor", "type": "string", "sa_type": "db.String(512)", "default": ""},
    {"path": "contexts.webWorker.renderer", "column": "contexts_web_worker_renderer", "label": "Contexts > Web Worker > Renderer", "type": "string", "sa_type": "db.String(512)", "default": ""},
]

# ── Detection fields (from FastBotDetectionDetails) ──

DETECTION_FIELDS = [
    {"name": "headlessChromeScreenResolution", "path": "fastBotDetectionDetails.headlessChromeScreenResolution.detected", "column": "det_headless_chrome_screen_resolution", "label": "Det: Headless Chrome Screen Resolution", "type": "boolean"},
    {"name": "hasWebdriver", "path": "fastBotDetectionDetails.hasWebdriver.detected", "column": "det_has_webdriver", "label": "Det: Has Webdriver", "type": "boolean"},
    {"name": "hasWebdriverWritable", "path": "fastBotDetectionDetails.hasWebdriverWritable.detected", "column": "det_has_webdriver_writable", "label": "Det: Has Webdriver Writable", "type": "boolean"},
    {"name": "hasSeleniumProperty", "path": "fastBotDetectionDetails.hasSeleniumProperty.detected", "column": "det_has_selenium_property", "label": "Det: Has Selenium Property", "type": "boolean"},
    {"name": "hasCDP", "path": "fastBotDetectionDetails.hasCDP.detected", "column": "det_has_cdp", "label": "Det: Has CDP", "type": "boolean"},
    {"name": "hasPlaywright", "path": "fastBotDetectionDetails.hasPlaywright.detected", "column": "det_has_playwright", "label": "Det: Has Playwright", "type": "boolean"},
    {"name": "hasImpossibleDeviceMemory", "path": "fastBotDetectionDetails.hasImpossibleDeviceMemory.detected", "column": "det_has_impossible_device_memory", "label": "Det: Has Impossible Device Memory", "type": "boolean"},
    {"name": "hasHighCPUCount", "path": "fastBotDetectionDetails.hasHighCPUCount.detected", "column": "det_has_high_cpu_count", "label": "Det: Has High CPU Count", "type": "boolean"},
    {"name": "hasMissingChromeObject", "path": "fastBotDetectionDetails.hasMissingChromeObject.detected", "column": "det_has_missing_chrome_object", "label": "Det: Has Missing Chrome Object", "type": "boolean"},
    {"name": "hasWebdriverIframe", "path": "fastBotDetectionDetails.hasWebdriverIframe.detected", "column": "det_has_webdriver_iframe", "label": "Det: Has Webdriver Iframe", "type": "boolean"},
    {"name": "hasWebdriverWorker", "path": "fastBotDetectionDetails.hasWebdriverWorker.detected", "column": "det_has_webdriver_worker", "label": "Det: Has Webdriver Worker", "type": "boolean"},
    {"name": "hasMismatchWebGLInWorker", "path": "fastBotDetectionDetails.hasMismatchWebGLInWorker.detected", "column": "det_has_mismatch_web_gl_in_worker", "label": "Det: Has Mismatch Web Gl In Worker", "type": "boolean"},
    {"name": "hasMismatchPlatformIframe", "path": "fastBotDetectionDetails.hasMismatchPlatformIframe.detected", "column": "det_has_mismatch_platform_iframe", "label": "Det: Has Mismatch Platform Iframe", "type": "boolean"},
    {"name": "hasMismatchPlatformWorker", "path": "fastBotDetectionDetails.hasMismatchPlatformWorker.detected", "column": "det_has_mismatch_platform_worker", "label": "Det: Has Mismatch Platform Worker", "type": "boolean"},
    {"name": "hasSwiftshaderRenderer", "path": "fastBotDetectionDetails.hasSwiftshaderRenderer.detected", "column": "det_has_swiftshader_renderer", "label": "Det: Has Swiftshader Renderer", "type": "boolean"},
    {"name": "hasUTCTimezone", "path": "fastBotDetectionDetails.hasUTCTimezone.detected", "column": "det_has_utc_timezone", "label": "Det: Has UTC Timezone", "type": "boolean"},
    {"name": "hasMismatchLanguages", "path": "fastBotDetectionDetails.hasMismatchLanguages.detected", "column": "det_has_mismatch_languages", "label": "Det: Has Mismatch Languages", "type": "boolean"},
    {"name": "hasInconsistentEtsl", "path": "fastBotDetectionDetails.hasInconsistentEtsl.detected", "column": "det_has_inconsistent_etsl", "label": "Det: Has Inconsistent ETSL", "type": "boolean"},
    {"name": "hasBotUserAgent", "path": "fastBotDetectionDetails.hasBotUserAgent.detected", "column": "det_has_bot_user_agent", "label": "Det: Has Bot User Agent", "type": "boolean"},
    {"name": "hasGPUMismatch", "path": "fastBotDetectionDetails.hasGPUMismatch.detected", "column": "det_has_gpu_mismatch", "label": "Det: Has GPU Mismatch", "type": "boolean"},
    {"name": "hasPlatformMismatch", "path": "fastBotDetectionDetails.hasPlatformMismatch.detected", "column": "det_has_platform_mismatch", "label": "Det: Has Platform Mismatch", "type": "boolean"},
]

# ── Top-level fingerprint fields ──

TOP_LEVEL_FIELDS = [
    {"path": "fsid", "column": "fsid", "label": "Fingerprint ID (fsid)", "type": "string"},
    {"path": "fastBotDetection", "column": "fast_bot_detection", "label": "Fast Bot Detection", "type": "boolean"},
    {"path": "url", "column": "url", "label": "Page URL", "type": "string"},
]

# ── Detection rule names (for seeding) ──

DETECTION_NAMES = [
    "headlessChromeScreenResolution",
    "hasWebdriver",
    "hasWebdriverWritable",
    "hasSeleniumProperty",
    "hasCDP",
    "hasPlaywright",
    "hasImpossibleDeviceMemory",
    "hasHighCPUCount",
    "hasMissingChromeObject",
    "hasWebdriverIframe",
    "hasWebdriverWorker",
    "hasMismatchWebGLInWorker",
    "hasMismatchPlatformIframe",
    "hasMismatchPlatformWorker",
    "hasSwiftshaderRenderer",
    "hasUTCTimezone",
    "hasMismatchLanguages",
    "hasInconsistentEtsl",
    "hasBotUserAgent",
    "hasGPUMismatch",
    "hasPlatformMismatch",
]

